{% set name = "gimli.units" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/gimli/archive/v{{ version }}.tar.gz
  sha256: 95cd52bc4df7f15c4035e8761b4d094afcaeb72598696fe8e961fcfb400c3ee1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - gimli=gimli._main:main
  skip: true  # [py<310]


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - numpy
    - udunits2
  run:
    - python
    - importlib-resources  # [py<312]
    - numpy
    - udunits2

test:
  imports:
    - gimli
  commands:
    - gimli --version
    - gimli --help
    - gimli --from=m --to=km

about:
  home: https://github.com/mcflugen/gimli
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Object-oriented Python interface for udunits2'
  description: |
    Object-oriented Python interface for udunits2
  dev_url: https://github.com/mcflugen/gimli

extra:
  recipe-maintainers:
    - mcflugen
