{% set name = "gimli.units" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/gimli/archive/v{{ version }}.tar.gz
  sha256: 09ff7f1c3c6c78d308a8f39869a596dbe10e099ee7a7484018f10608726c9a3f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - gimli=gimli._main:main

requirements:
  build:
    - python >=3.10                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python >=3.10
    - pip
    - cython
    - numpy
    - udunits2
  run:
    - python >=3.10
    - importlib-resources  # [py<312]
    - numpy
    - udunits2

test:
  imports:
    - gimli
  commands:
    - gimli --version
    - gimli --help
    - gimli --from=m --to=km

about:
  home: https://github.com/mcflugen/gimli
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Object-oriented Python interface for udunits2'
  description: |
    Object-oriented Python interface for udunits2
  dev_url: https://github.com/mcflugen/gimli

extra:
  recipe-maintainers:
    - mcflugen
