{% set name = "gimli.units" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/gimli/archive/v{{ version }}.tar.gz
  sha256: ef2f64f1ccb212e85fa248e5413be43878b9a0b9404bceb5d9ad641a91306b50

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - gimli=gimli.cli:gimli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - udunits2
  run:
    - python
    - click
    - numpy
    - setuptools
    - udunits2

test:
  imports:
    - gimli
  commands:
    - gimli --version
    - gimli --help
    - gimli
    - gimli --from=m --to=km --data=1,2,3,4,5

about:
  home: https://github.com/mcflugen/gimli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Object-oriented Python interface for udunits2'
  description: |
    Object-oriented Python interface for udunits2
  dev_url: https://github.com/mcflugen/gimli

extra:
  recipe-maintainers:
    - mcflugen
